// Auto-generated by tool://tool-creator at 2026-06-24T14:56:00.614Z
// URI: tool://finance-quote
// Description: 查询股票实时行情

export default {
      async execute(action, params) {
        if (action === 'quote') return { symbol: params.symbol, price: 100 };
        throw new Error('unknown');
      },
    };