export const CONFIG_CATALOG = [
  { key: 'role', env: 'PERSENG_ROLE', type: 'string', defaultValue: 'jiangziya', category: 'core', description: '默认角色 ID', doctorVisible: true },
  { key: 'model', env: 'PERSENG_MODEL', type: 'string', defaultValue: 'claude-sonnet-4-20250514', category: 'core', description: '默认模型名', doctorVisible: true },
  { key: 'modelStrategy.idle', env: 'PERSENG_MODEL_IDLE', type: 'string', defaultValue: '', category: 'core', description: 'idle 阶段模型' },
  { key: 'modelStrategy.goal', env: 'PERSENG_MODEL_GOAL', type: 'string', defaultValue: '', category: 'core', description: 'goal 阶段模型' },
  { key: 'modelStrategy.planning', env: 'PERSENG_MODEL_PLANNING', type: 'string', defaultValue: '', category: 'core', description: 'planning 阶段模型' },
  { key: 'modelStrategy.execution', env: 'PERSENG_MODEL_EXECUTION', type: 'string', defaultValue: '', category: 'core', description: 'execution 阶段模型' },
  { key: 'modelStrategy.reflection', env: 'PERSENG_MODEL_REFLECTION', type: 'string', defaultValue: '', category: 'core', description: 'reflection 阶段模型' },
  { key: 'anthropicApiKey', env: 'ANTHROPIC_API_KEY', type: 'string', defaultValue: '', category: 'llm', description: 'Anthropic API Key', secret: true, doctorVisible: true },
  { key: 'openaiApiKey', env: 'OPENAI_API_KEY', type: 'string', defaultValue: '', category: 'llm', description: 'OpenAI 兼容 API Key', secret: true, doctorVisible: true },
  { key: 'apiBase', env: 'PERSENG_API_BASE', type: 'string', defaultValue: '', category: 'llm', description: 'OpenAI 兼容端点 Base URL', doctorVisible: true },
  { key: 'llmRetryEnabled', env: 'PERSENG_LLM_RETRY', type: 'boolean', defaultValue: true, category: 'llm', description: '是否启用 LLM retry' },
  { key: 'llmMaxRetries', env: 'PERSENG_LLM_MAX_RETRIES', type: 'number', defaultValue: 3, category: 'llm', description: 'LLM 最大重试次数' },
  { key: 'llmBaseDelayMs', env: 'PERSENG_LLM_BASE_DELAY_MS', type: 'number', defaultValue: 500, category: 'llm', description: 'LLM retry 基础退避毫秒数' },
  { key: 'feishuAppId', env: 'FEISHU_APP_ID', type: 'string', defaultValue: '', category: 'feishu', description: '飞书应用 App ID', doctorVisible: true },
  { key: 'feishuAppSecret', env: 'FEISHU_APP_SECRET', type: 'string', defaultValue: '', category: 'feishu', description: '飞书应用 App Secret', secret: true, doctorVisible: true },
  { key: 'feishuBotOpenId', env: 'FEISHU_BOT_OPEN_ID', type: 'string', defaultValue: '', category: 'feishu', description: '机器人 open_id' },
  { key: 'feishuAllowUsers', env: 'PERSENG_FEISHU_ALLOW_USERS', type: 'csv', defaultValue: [], category: 'feishu', description: '允许访问的用户 ID 列表' },
  { key: 'feishuAllowGroups', env: 'PERSENG_FEISHU_ALLOW_GROUPS', type: 'csv', defaultValue: [], category: 'feishu', description: '允许访问的群 ID 列表' },
  { key: 'feishuRoleAdmins', env: 'PERSENG_FEISHU_ROLE_ADMINS', type: 'csv', defaultValue: [], category: 'feishu', description: '允许切换角色的管理员列表' },
  { key: 'asrModel', env: 'PERSENG_ASR_MODEL', type: 'string', defaultValue: 'whisper-1', category: 'feishu', description: '语音转写模型' },
  { key: 'gbrainUrl', env: 'GBRAIN_URL', type: 'string', defaultValue: '', category: 'gbrain', description: 'GBrain 服务 URL', doctorVisible: true },
  { key: 'gbrainHttpToken', env: 'GBRAIN_HTTP_TOKEN', type: 'string', defaultValue: '', category: 'gbrain', description: 'GBrain Bearer Token', secret: true },
  { key: 'gbrainBrainArea', env: 'GBRAIN_BRAIN_AREA', type: 'string', defaultValue: 'perseng', category: 'gbrain', description: '默认脑区' },
  { key: 'gbrainTimeoutMs', env: 'GBRAIN_TIMEOUT_MS', type: 'number', defaultValue: 15000, category: 'gbrain', description: 'GBrain 请求超时毫秒数' },
  { key: 'httpHost', env: 'PERSENG_HTTP_HOST', type: 'string', defaultValue: '127.0.0.1', category: 'http', description: 'HTTP 管理服务监听地址', doctorVisible: true },
  { key: 'httpPort', env: 'PERSENG_HTTP_PORT', type: 'number', defaultValue: 7717, category: 'http', description: 'HTTP 管理服务监听端口', doctorVisible: true },
  { key: 'httpToken', env: 'PERSENG_HTTP_TOKEN', type: 'string', defaultValue: '', category: 'http', description: 'HTTP / WebSocket 鉴权 token', secret: true, doctorVisible: true },
  { key: 'httpMaxSessions', env: 'PERSENG_HTTP_MAX_SESSIONS', type: 'number', defaultValue: 20, category: 'http', description: '最大 Web 会话数' },
  { key: 'dataDir', env: 'PERSENG_CLI_DATA_DIR', type: 'path', defaultValue: '~/.perseng-cli', category: 'storage', description: '统一数据根目录', doctorVisible: true },
  { key: 'cognitionDir', env: 'PERSENG_CLI_COGNITION_DIR', type: 'path', defaultValue: '', category: 'storage', description: '记忆目录覆盖' },
  { key: 'rolexDir', env: 'PERSENG_CLI_ROLEX_DIR', type: 'path', defaultValue: '', category: 'storage', description: 'RoleX 目录覆盖' },
  { key: 'blackboardDir', env: 'PERSENG_CLI_BLACKBOARD_DIR', type: 'path', defaultValue: '', category: 'storage', description: 'Blackboard 目录覆盖' },
  { key: 'timelineDir', env: 'PERSENG_CLI_TIMELINE_DIR', type: 'path', defaultValue: '', category: 'storage', description: '时间线目录覆盖' },
  { key: 'allowNetwork', env: 'PERSENG_ALLOW_NETWORK', type: 'boolean', defaultValue: false, category: 'policy', description: '是否允许外网访问' },
  { key: 'allowPathOutsideCwd', env: 'PERSENG_ALLOW_PATH_OUTSIDE_CWD', type: 'boolean', defaultValue: false, category: 'policy', description: '是否允许访问工作目录外路径' },
  { key: 'blockRunCommand', env: 'PERSENG_BLOCK_RUN_COMMAND', type: 'boolean', defaultValue: false, category: 'policy', description: '是否禁用 run_command' },
  { key: 'runCommandAllowlist', env: 'PERSENG_RUN_COMMAND_ALLOWLIST', type: 'csv', defaultValue: [], category: 'policy', description: '允许执行的命令白名单' },
  { key: 'followSymlinks', env: 'PERSENG_FOLLOW_SYMLINKS', type: 'boolean', defaultValue: false, category: 'policy', description: '是否跟随符号链接' },
  { key: 'logLevel', env: 'PERSENG_LOG_LEVEL', type: 'string', defaultValue: 'info', category: 'observability', description: '日志级别' },
  { key: 'logPretty', env: 'PERSENG_LOG_PRETTY', type: 'boolean', defaultValue: false, category: 'observability', description: '是否启用人类可读日志' },
  { key: 'debug', env: 'PERSENG_DEBUG', type: 'boolean', defaultValue: false, category: 'observability', description: '是否启用 debug 模式' },
  { key: 'maxMemoriesPerRole', env: 'PERSENG_MAX_MEMORIES_PER_ROLE', type: 'number', defaultValue: 500, category: 'limits', description: '每角色最大记忆数' },
  { key: 'rolesCacheLimit', env: 'PERSENG_ROLES_CACHE_LIMIT', type: 'number', defaultValue: 32, category: 'limits', description: '角色缓存上限' },
];

export function getDoctorVisibleConfigFields() {
  return CONFIG_CATALOG.filter((item) => item.doctorVisible);
}
